#############################################################################
# Makefile for building: Nougat
# Generated by qmake (1.07a) (Qt 3.3.8) on: Mon Nov 21 11:06:28 2016
# Project:  Nougat.pro
# Template: app
# Command: $(QMAKE) -o Makefile Nougat.pro
#############################################################################

####### Compiler, tools and options

CC       = cc
CXX      = c++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -Os  -D__DARWIN_X11__ -DQT_NO_DEBUG
CXXFLAGS = -pipe -Wall -W -Os  -D__DARWIN_X11__ -DQT_NO_DEBUG
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/sw/lib/qt3/mkspecs/default -I. -I/usr/local/include -I/sw/lib/qt3/include -I$(QTDIR)/include
LINK     = c++
LFLAGS   = -Wl,-dylib_file,/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib:/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib -prebind
LIBS     = $(SUBLIBS) -L/sw/lib -L$(QTDIR)/lib -L/usr/X11R6/lib -L/usr/local/lib -lgsl -lqt-mt -lXext -lX11 -lm
AR       = /usr/bin/ar cq
RANLIB   = /usr/bin/ranlib -s
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = /bin/cp -f
COPY_FILE= /bin/cp -f
COPY_DIR = /bin/cp -f -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = /bin/rm -f
SYMLINK  = ln -sf
DEL_DIR  = /bin/rmdir
MOVE     = /bin/mv -f
CHK_DIR_EXISTS= /bin/test -d
MKDIR    = /bin/mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = GeometryLibrary/likelihood/graphstatistics.h \
		GeometryLibrary/likelihood/lgraph.h \
		GeometryLibrary/likelihood/likelihood.h \
		GeometryLibrary/likelihood/spline.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/cutil.h \
		GeometryLibrary/misc/random.h \
		GeometryLibrary/misc/util.h \
		GeometryLibrary/models/cylindermodel.h \
		GeometryLibrary/models/model.h \
		GeometryLibrary/models/models.h \
		GeometryLibrary/models/multifractalmodel.h \
		GeometryLibrary/models/octree.h \
		GeometryLibrary/models/regularnoisemodel.h \
		GeometryLibrary/models/voidmodel.h \
		GeometryLibrary/models/xyzmodel.h \
		GeometryLibrary/noise.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/perlin.h \
		GeometryLibrary/simplex.h \
		GeometryLibrary/simplexnoise.h \
		GeometryLibrary/dtalikelihood.h \
		GeometryLibrary/particle.h \
		commandparser.h \
		GeometryLibrary/misc/distancetoatommap.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/misc/points.h \
		GeometryLibrary/measures/distancetoatom.h \
		GeometryLibrary/measures/measure.h
SOURCES = GeometryLibrary/likelihood/graphstatistics.cpp \
		GeometryLibrary/likelihood/lgraph.cpp \
		GeometryLibrary/likelihood/likelihood.cpp \
		GeometryLibrary/logger.cpp \
		GeometryLibrary/misc/cutil.cpp \
		GeometryLibrary/misc/util.cpp \
		GeometryLibrary/models/cylindermodel.cpp \
		GeometryLibrary/models/model.cpp \
		GeometryLibrary/models/multifractalmodel.cpp \
		GeometryLibrary/models/octree.cpp \
		GeometryLibrary/models/regularnoisemodel.cpp \
		GeometryLibrary/models/voidmodel.cpp \
		GeometryLibrary/models/xyzmodel.cpp \
		GeometryLibrary/noise.cpp \
		GeometryLibrary/parameters.cpp \
		GeometryLibrary/perlin.cpp \
		GeometryLibrary/simplex.cpp \
		GeometryLibrary/simplexnoise.cpp \
		GeometryLibrary/dtalikelihood.cpp \
		GeometryLibrary/particle.cpp \
		nougat.cpp \
		commandparser.cpp \
		GeometryLibrary/misc/distancetoatommap.cpp \
		GeometryLibrary/misc/grid.cpp \
		GeometryLibrary/misc/points.cpp \
		GeometryLibrary/measures/distancetoatom.cpp \
		GeometryLibrary/measures/measure.cpp
OBJECTS = graphstatistics.o \
		lgraph.o \
		likelihood.o \
		logger.o \
		cutil.o \
		util.o \
		cylindermodel.o \
		model.o \
		multifractalmodel.o \
		octree.o \
		regularnoisemodel.o \
		voidmodel.o \
		xyzmodel.o \
		noise.o \
		parameters.o \
		perlin.o \
		simplex.o \
		simplexnoise.o \
		dtalikelihood.o \
		particle.o \
		nougat.o \
		commandparser.o \
		distancetoatommap.o \
		grid.o \
		points.o \
		distancetoatom.o \
		measure.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = GeometryLibrary/models/moc_cylindermodel.cpp \
		GeometryLibrary/models/moc_model.cpp \
		GeometryLibrary/models/moc_octree.cpp \
		GeometryLibrary/models/moc_regularnoisemodel.cpp \
		GeometryLibrary/models/moc_xyzmodel.cpp \
		GeometryLibrary/moc_noise.cpp \
		GeometryLibrary/moc_parameters.cpp \
		GeometryLibrary/moc_perlin.cpp \
		GeometryLibrary/moc_simplex.cpp
OBJMOC = moc_cylindermodel.o \
		moc_model.o \
		moc_octree.o \
		moc_regularnoisemodel.o \
		moc_xyzmodel.o \
		moc_noise.o \
		moc_parameters.o \
		moc_perlin.o \
		moc_simplex.o
DIST	   = Nougat.pro
QMAKE_TARGET = Nougat
DESTDIR  = 
TARGET   = Nougat

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: Nougat.pro  /sw/lib/qt3/mkspecs/default/qmake.conf 
	$(QMAKE) -o Makefile Nougat.pro
qmake: 
	@$(QMAKE) -o Makefile Nougat.pro

dist: 
	@mkdir -p .tmp/Nougat && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/Nougat/ && ( cd `dirname .tmp/Nougat` && $(TAR) Nougat.tar Nougat && $(GZIP) Nougat.tar ) && $(MOVE) `dirname .tmp/Nougat`/Nougat.tar.gz . && $(DEL_FILE) -r .tmp/Nougat

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

graphstatistics.o: GeometryLibrary/likelihood/graphstatistics.cpp GeometryLibrary/likelihood/graphstatistics.h \
		GeometryLibrary/likelihood/lgraph.h \
		GeometryLibrary/likelihood/spline.h \
		GeometryLibrary/misc/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphstatistics.o GeometryLibrary/likelihood/graphstatistics.cpp

lgraph.o: GeometryLibrary/likelihood/lgraph.cpp GeometryLibrary/likelihood/lgraph.h \
		GeometryLibrary/likelihood/spline.h \
		GeometryLibrary/misc/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lgraph.o GeometryLibrary/likelihood/lgraph.cpp

likelihood.o: GeometryLibrary/likelihood/likelihood.cpp GeometryLibrary/likelihood/likelihood.h \
		GeometryLibrary/models/model.h \
		GeometryLibrary/misc/random.h \
		GeometryLibrary/likelihood/lgraph.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/likelihood/graphstatistics.h \
		GeometryLibrary/likelihood/spline.h \
		GeometryLibrary/misc/util.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o likelihood.o GeometryLibrary/likelihood/likelihood.cpp

logger.o: GeometryLibrary/logger.cpp GeometryLibrary/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o GeometryLibrary/logger.cpp

cutil.o: GeometryLibrary/misc/cutil.cpp GeometryLibrary/misc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cutil.o GeometryLibrary/misc/cutil.cpp

util.o: GeometryLibrary/misc/util.cpp GeometryLibrary/misc/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o GeometryLibrary/misc/util.cpp

cylindermodel.o: GeometryLibrary/models/cylindermodel.cpp GeometryLibrary/models/cylindermodel.h \
		GeometryLibrary/models/model.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cylindermodel.o GeometryLibrary/models/cylindermodel.cpp

model.o: GeometryLibrary/models/model.cpp GeometryLibrary/models/models.h \
		GeometryLibrary/misc/random.h \
		GeometryLibrary/likelihood/lgraph.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/models/model.h \
		GeometryLibrary/models/multifractalmodel.h \
		GeometryLibrary/models/cylindermodel.h \
		GeometryLibrary/models/voidmodel.h \
		GeometryLibrary/models/regularnoisemodel.h \
		GeometryLibrary/models/octree.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h \
		GeometryLibrary/models/xyzmodel.h \
		GeometryLibrary/noise.h \
		GeometryLibrary/likelihood/spline.h \
		GeometryLibrary/misc/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o GeometryLibrary/models/model.cpp

multifractalmodel.o: GeometryLibrary/models/multifractalmodel.cpp GeometryLibrary/models/multifractalmodel.h \
		GeometryLibrary/noise.h \
		GeometryLibrary/models/regularnoisemodel.h \
		GeometryLibrary/models/model.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multifractalmodel.o GeometryLibrary/models/multifractalmodel.cpp

octree.o: GeometryLibrary/models/octree.cpp GeometryLibrary/models/octree.h \
		GeometryLibrary/models/regularnoisemodel.h \
		GeometryLibrary/models/model.h \
		GeometryLibrary/models/xyzmodel.h \
		GeometryLibrary/noise.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o octree.o GeometryLibrary/models/octree.cpp

regularnoisemodel.o: GeometryLibrary/models/regularnoisemodel.cpp GeometryLibrary/models/regularnoisemodel.h \
		GeometryLibrary/simplex.h \
		GeometryLibrary/perlin.h \
		GeometryLibrary/misc/random.h \
		GeometryLibrary/models/model.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h \
		GeometryLibrary/noise.h \
		GeometryLibrary/simplexnoise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o regularnoisemodel.o GeometryLibrary/models/regularnoisemodel.cpp

voidmodel.o: GeometryLibrary/models/voidmodel.cpp GeometryLibrary/models/voidmodel.h \
		GeometryLibrary/models/model.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o voidmodel.o GeometryLibrary/models/voidmodel.cpp

xyzmodel.o: GeometryLibrary/models/xyzmodel.cpp GeometryLibrary/models/xyzmodel.h \
		GeometryLibrary/models/regularnoisemodel.h \
		GeometryLibrary/misc/random.h \
		GeometryLibrary/models/model.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xyzmodel.o GeometryLibrary/models/xyzmodel.cpp

noise.o: GeometryLibrary/noise.cpp GeometryLibrary/noise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o noise.o GeometryLibrary/noise.cpp

parameters.o: GeometryLibrary/parameters.cpp GeometryLibrary/parameters.h \
		GeometryLibrary/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameters.o GeometryLibrary/parameters.cpp

perlin.o: GeometryLibrary/perlin.cpp GeometryLibrary/perlin.h \
		GeometryLibrary/noise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o perlin.o GeometryLibrary/perlin.cpp

simplex.o: GeometryLibrary/simplex.cpp GeometryLibrary/simplex.h \
		GeometryLibrary/noise.h \
		GeometryLibrary/simplexnoise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simplex.o GeometryLibrary/simplex.cpp

simplexnoise.o: GeometryLibrary/simplexnoise.cpp GeometryLibrary/simplexnoise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simplexnoise.o GeometryLibrary/simplexnoise.cpp

dtalikelihood.o: GeometryLibrary/dtalikelihood.cpp GeometryLibrary/dtalikelihood.h \
		GeometryLibrary/models/models.h \
		GeometryLibrary/likelihood/likelihood.h \
		GeometryLibrary/particle.h \
		GeometryLibrary/measures/distancetoatom.h \
		GeometryLibrary/likelihood/lgraph.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/likelihood/graphstatistics.h \
		GeometryLibrary/likelihood/spline.h \
		GeometryLibrary/misc/util.h \
		GeometryLibrary/models/model.h \
		GeometryLibrary/models/multifractalmodel.h \
		GeometryLibrary/models/cylindermodel.h \
		GeometryLibrary/models/voidmodel.h \
		GeometryLibrary/models/regularnoisemodel.h \
		GeometryLibrary/models/octree.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h \
		GeometryLibrary/models/xyzmodel.h \
		GeometryLibrary/noise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dtalikelihood.o GeometryLibrary/dtalikelihood.cpp

particle.o: GeometryLibrary/particle.cpp GeometryLibrary/particle.h \
		GeometryLibrary/misc/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o particle.o GeometryLibrary/particle.cpp

nougat.o: nougat.cpp commandparser.h \
		GeometryLibrary/distancetoatom.h \
		GeometryLibrary/particle.h \
		GeometryLibrary/dtalikelihood.h \
		GeometryLibrary/likelihood/lgraph.h \
		GeometryLibrary/models/regularnoisemodel.h \
		GeometryLibrary/likelihood/likelihood.h \
		GeometryLibrary/measures/distancetoatom.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/likelihood/graphstatistics.h \
		GeometryLibrary/likelihood/spline.h \
		GeometryLibrary/misc/util.h \
		GeometryLibrary/models/model.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h

commandparser.o: commandparser.cpp commandparser.h \
		GeometryLibrary/distancetoatom.h \
		GeometryLibrary/particle.h \
		GeometryLibrary/dtalikelihood.h \
		GeometryLibrary/likelihood/lgraph.h \
		GeometryLibrary/models/regularnoisemodel.h \
		GeometryLibrary/likelihood/likelihood.h \
		GeometryLibrary/measures/distancetoatom.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/likelihood/graphstatistics.h \
		GeometryLibrary/likelihood/spline.h \
		GeometryLibrary/misc/util.h \
		GeometryLibrary/models/model.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h

distancetoatommap.o: GeometryLibrary/misc/distancetoatommap.cpp GeometryLibrary/misc/distancetoatommap.h \
		GeometryLibrary/misc/points.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/measures/distancetoatom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o distancetoatommap.o GeometryLibrary/misc/distancetoatommap.cpp

grid.o: GeometryLibrary/misc/grid.cpp GeometryLibrary/misc/grid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grid.o GeometryLibrary/misc/grid.cpp

points.o: GeometryLibrary/misc/points.cpp GeometryLibrary/misc/points.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o points.o GeometryLibrary/misc/points.cpp

distancetoatom.o: GeometryLibrary/measures/distancetoatom.cpp GeometryLibrary/measures/distancetoatom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o distancetoatom.o GeometryLibrary/measures/distancetoatom.cpp

measure.o: GeometryLibrary/measures/measure.cpp GeometryLibrary/measures/measure.h \
		GeometryLibrary/models/model.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o measure.o GeometryLibrary/measures/measure.cpp

moc_cylindermodel.o: GeometryLibrary/models/moc_cylindermodel.cpp  GeometryLibrary/models/cylindermodel.h GeometryLibrary/models/model.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cylindermodel.o GeometryLibrary/models/moc_cylindermodel.cpp

moc_model.o: GeometryLibrary/models/moc_model.cpp  GeometryLibrary/models/model.h GeometryLibrary/parameters.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_model.o GeometryLibrary/models/moc_model.cpp

moc_octree.o: GeometryLibrary/models/moc_octree.cpp  GeometryLibrary/models/octree.h GeometryLibrary/models/model.h \
		GeometryLibrary/models/xyzmodel.h \
		GeometryLibrary/noise.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_octree.o GeometryLibrary/models/moc_octree.cpp

moc_regularnoisemodel.o: GeometryLibrary/models/moc_regularnoisemodel.cpp  GeometryLibrary/models/regularnoisemodel.h GeometryLibrary/models/model.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_regularnoisemodel.o GeometryLibrary/models/moc_regularnoisemodel.cpp

moc_xyzmodel.o: GeometryLibrary/models/moc_xyzmodel.cpp  GeometryLibrary/models/xyzmodel.h GeometryLibrary/models/model.h \
		GeometryLibrary/parameters.h \
		GeometryLibrary/misc/cinifile.h \
		GeometryLibrary/misc/grid.h \
		GeometryLibrary/logger.h \
		GeometryLibrary/misc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_xyzmodel.o GeometryLibrary/models/moc_xyzmodel.cpp

moc_noise.o: GeometryLibrary/moc_noise.cpp  GeometryLibrary/noise.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_noise.o GeometryLibrary/moc_noise.cpp

moc_parameters.o: GeometryLibrary/moc_parameters.cpp  GeometryLibrary/parameters.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parameters.o GeometryLibrary/moc_parameters.cpp

moc_perlin.o: GeometryLibrary/moc_perlin.cpp  GeometryLibrary/perlin.h GeometryLibrary/noise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_perlin.o GeometryLibrary/moc_perlin.cpp

moc_simplex.o: GeometryLibrary/moc_simplex.cpp  GeometryLibrary/simplex.h GeometryLibrary/noise.h \
		GeometryLibrary/simplexnoise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_simplex.o GeometryLibrary/moc_simplex.cpp

GeometryLibrary/models/moc_cylindermodel.cpp: $(MOC) GeometryLibrary/models/cylindermodel.h
	$(MOC) GeometryLibrary/models/cylindermodel.h -o GeometryLibrary/models/moc_cylindermodel.cpp

GeometryLibrary/models/moc_model.cpp: $(MOC) GeometryLibrary/models/model.h
	$(MOC) GeometryLibrary/models/model.h -o GeometryLibrary/models/moc_model.cpp

GeometryLibrary/models/moc_octree.cpp: $(MOC) GeometryLibrary/models/octree.h
	$(MOC) GeometryLibrary/models/octree.h -o GeometryLibrary/models/moc_octree.cpp

GeometryLibrary/models/moc_regularnoisemodel.cpp: $(MOC) GeometryLibrary/models/regularnoisemodel.h
	$(MOC) GeometryLibrary/models/regularnoisemodel.h -o GeometryLibrary/models/moc_regularnoisemodel.cpp

GeometryLibrary/models/moc_xyzmodel.cpp: $(MOC) GeometryLibrary/models/xyzmodel.h
	$(MOC) GeometryLibrary/models/xyzmodel.h -o GeometryLibrary/models/moc_xyzmodel.cpp

GeometryLibrary/moc_noise.cpp: $(MOC) GeometryLibrary/noise.h
	$(MOC) GeometryLibrary/noise.h -o GeometryLibrary/moc_noise.cpp

GeometryLibrary/moc_parameters.cpp: $(MOC) GeometryLibrary/parameters.h
	$(MOC) GeometryLibrary/parameters.h -o GeometryLibrary/moc_parameters.cpp

GeometryLibrary/moc_perlin.cpp: $(MOC) GeometryLibrary/perlin.h
	$(MOC) GeometryLibrary/perlin.h -o GeometryLibrary/moc_perlin.cpp

GeometryLibrary/moc_simplex.cpp: $(MOC) GeometryLibrary/simplex.h
	$(MOC) GeometryLibrary/simplex.h -o GeometryLibrary/moc_simplex.cpp

####### Install

install:  

uninstall:  

