#!/bin/bash  

bins=25
python plot_mc.py 1d 0 mc.txt persistence $bins 
echo "1/8"
python plot_mc.py 1d 0 mc.txt threshold $bins
echo "2/8"
python plot_mc.py 1d 0 mc.txt scale $bins
echo "3/8"
python plot_mc.py 1d 0 mc.txt steepness $bins
echo "4/8"

x=1024
y=768

dx=$((x /2))
dy=$((y /2))

convert -size ${x}x${y} xc:white comp_resize.png
echo "5/8"
composite -geometry ${dx}x${dy}+0+0 mcmc_1d_persistence.eps comp_resize.png comp_resize.png
echo "6/8"
composite -geometry ${dx}x${dy}+${dx}+0 mcmc_1d_threshold.eps comp_resize.png comp_resize.png
echo "7/8"
composite -geometry ${dx}x${dy}+0+${dy} mcmc_1d_scale.eps comp_resize.png comp_resize.png
echo "8/8"
composite -geometry ${dx}x${dy}+${dx}+${dy} mcmc_1d_steepness.eps comp_resize.png comp_resize.png

mv comp_resize.png 1d.png
open 1d.png
